# Generated by Django 2.2.4 on 2019-09-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190907_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.TextField(max_length=1000, null=True, verbose_name='Adress:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
