# Generated by Django 2.2.4 on 2019-09-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20190903_1542'),
        ('users', '0005_auto_20190908_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Cart'),
        ),
    ]
