# Generated by Django 2.2.4 on 2019-09-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
    ]
