# Generated by Django 2.2.4 on 2019-09-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/no-image-icon.png', null=True, upload_to='product/', verbose_name='Media'),
        ),
    ]
